import type { ExperienceId, ExperienceMeta } from "./types";

type ProfileFields = Pick<
  ExperienceMeta,
  | "needs"
  | "layer"
  | "feel"
  | "sensory"
  | "speed"
  | "predictability"
  | "cognitive"
  | "hapticBest"
>;

export const EXPERIENCE_PROFILES: Record<ExperienceId, ProfileFields> = {
  "mesh-lattice": {
    needs: ["focus", "explore"],
    layer: "world",
    feel: "Orbit, zoom, and let a song move the lattice.",
    sensory: { visual: 3, audio: 2, haptic: 1 },
    speed: "medium",
    predictability: "medium",
    cognitive: "medium",
  },
  "sand-tray": {
    needs: ["settle", "focus"],
    layer: "environment",
    feel: "Slow, repetitive, tactile.",
    sensory: { visual: 2, audio: 1, haptic: 2 },
    speed: "slow",
    predictability: "high",
    cognitive: "low",
  },
  "silk-fluid": {
    needs: ["settle", "focus"],
    layer: "environment",
    feel: "Flowing color, gentle drag.",
    sensory: { visual: 3, audio: 1, haptic: 1 },
    speed: "slow",
    predictability: "medium",
    cognitive: "low",
  },
  "ripple-pool": {
    needs: ["settle"],
    layer: "environment",
    feel: "Soft water, slow ripples.",
    sensory: { visual: 2, audio: 1, haptic: 1 },
    speed: "slow",
    predictability: "high",
    cognitive: "low",
  },
  "elastic-web": {
    needs: ["stimulate", "focus"],
    layer: "environment",
    feel: "Pull and release, harmonic wobble.",
    sensory: { visual: 2, audio: 2, haptic: 2 },
    speed: "medium",
    predictability: "high",
    cognitive: "medium",
  },
  "magnetic-field": {
    needs: ["stimulate", "focus"],
    layer: "environment",
    feel: "Drag fields, filings swarm.",
    sensory: { visual: 2, audio: 1, haptic: 2 },
    speed: "medium",
    predictability: "medium",
    cognitive: "medium",
  },
  "gear-mesh": {
    needs: ["stimulate", "hands"],
    layer: "environment",
    feel: "Crank, mesh, grind.",
    sensory: { visual: 2, audio: 2, haptic: 3 },
    speed: "medium",
    predictability: "high",
    cognitive: "medium",
    hapticBest: true,
  },
  "orbit-beads": {
    needs: ["settle", "stimulate"],
    layer: "environment",
    feel: "Fling beads into slow orbits.",
    sensory: { visual: 2, audio: 1, haptic: 1 },
    speed: "medium",
    predictability: "medium",
    cognitive: "low",
  },
  "pulse-pads": {
    needs: ["stimulate", "hands"],
    layer: "object",
    feel: "Tap pads, each its own tone.",
    sensory: { visual: 2, audio: 3, haptic: 3 },
    speed: "fast",
    predictability: "high",
    cognitive: "low",
    hapticBest: true,
  },
  "stone-polish": {
    needs: ["settle", "focus"],
    layer: "environment",
    feel: "Rub until the shine sweeps across.",
    sensory: { visual: 2, audio: 1, haptic: 2 },
    speed: "slow",
    predictability: "high",
    cognitive: "low",
  },
  "slider-loom": {
    needs: ["focus"],
    layer: "environment",
    feel: "Repetitive shuttle, cords ring back.",
    sensory: { visual: 2, audio: 2, haptic: 2 },
    speed: "medium",
    predictability: "high",
    cognitive: "medium",
  },
  "pen-clicker": {
    needs: ["hands", "stimulate"],
    layer: "object",
    feel: "Tip out, tip in, again.",
    sensory: { visual: 1, audio: 2, haptic: 3 },
    speed: "fast",
    predictability: "high",
    cognitive: "low",
    hapticBest: true,
  },
  "light-switch": {
    needs: ["hands", "stimulate"],
    layer: "object",
    feel: "Flip the paddle, room answers.",
    sensory: { visual: 2, audio: 2, haptic: 2 },
    speed: "fast",
    predictability: "high",
    cognitive: "low",
    hapticBest: true,
  },
  "lamp-toggle": {
    needs: ["hands"],
    layer: "object",
    feel: "Pull the cord, light snaps.",
    sensory: { visual: 2, audio: 2, haptic: 2 },
    speed: "medium",
    predictability: "high",
    cognitive: "low",
    hapticBest: true,
  },
  "keyboard-thock": {
    needs: ["stimulate", "hands"],
    layer: "object",
    feel: "Chunky keys, soft thock.",
    sensory: { visual: 2, audio: 3, haptic: 2 },
    speed: "fast",
    predictability: "high",
    cognitive: "low",
    hapticBest: true,
  },
  "mouse-click": {
    needs: ["hands", "stimulate"],
    layer: "object",
    feel: "Left, right, wheel — desktop comfort.",
    sensory: { visual: 1, audio: 2, haptic: 2 },
    speed: "fast",
    predictability: "high",
    cognitive: "low",
    hapticBest: true,
  },
  "big-button": {
    needs: ["hands", "stimulate"],
    layer: "object",
    feel: "One deep press, soft rebound.",
    sensory: { visual: 2, audio: 2, haptic: 3 },
    speed: "medium",
    predictability: "high",
    cognitive: "low",
    hapticBest: true,
  },
  "bubble-wrap": {
    needs: ["stimulate", "hands"],
    layer: "object",
    feel: "Pop every blister, sheet refills.",
    sensory: { visual: 2, audio: 2, haptic: 2 },
    speed: "fast",
    predictability: "high",
    cognitive: "low",
    hapticBest: true,
  },
  "fidget-cube": {
    needs: ["stimulate", "hands"],
    layer: "object",
    feel: "Turn the cube, each face a fidget.",
    sensory: { visual: 2, audio: 2, haptic: 3 },
    speed: "medium",
    predictability: "medium",
    cognitive: "medium",
    hapticBest: true,
  },
  "fidget-spinner": {
    needs: ["stimulate", "hands"],
    layer: "object",
    feel: "Flick hard, coast to still.",
    sensory: { visual: 2, audio: 1, haptic: 2 },
    speed: "fast",
    predictability: "high",
    cognitive: "low",
    hapticBest: true,
  },
  zipper: {
    needs: ["hands"],
    layer: "object",
    feel: "Teeth chatter open and shut.",
    sensory: { visual: 2, audio: 2, haptic: 2 },
    speed: "medium",
    predictability: "high",
    cognitive: "low",
    hapticBest: true,
  },
};

export function applyProfile<T extends { id: ExperienceId }>(meta: T): T & ProfileFields {
  const profile = EXPERIENCE_PROFILES[meta.id];
  return { ...meta, ...profile };
}
